# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.mohesr.example.com:
  peer1.mohesr.example.com:
  peer0.asu.example.com:
  peer1.asu.example.com:

networks:
  byfn:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - byfn

  peer0.mohesr.example.com:
    container_name: peer0.mohesr.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.mohesr.example.com
    networks:
      - byfn

  peer1.mohesr.example.com:
    container_name: peer1.mohesr.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.mohesr.example.com
    networks:
      - byfn

  peer0.asu.example.com:
    container_name: peer0.asu.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.asu.example.com
    networks:
      - byfn

  peer1.asu.example.com:
    container_name: peer1.asu.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.asu.example.com
    networks:
      - byfn

  ca.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.mohesr.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/56bc02e1bfdd2d2e7d28923e5fbc86a9d0088b074f5fc0d2c77a88467971df8d_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/mohesr.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.example.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.mohesr.example.com:7051
      - CORE_PEER_LOCALMSPID=MohesrMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mohesr.example.com/peers/peer0.mohesr.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mohesr.example.com/peers/peer0.mohesr.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mohesr.example.com/peers/peer0.mohesr.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mohesr.example.com/users/Admin@mohesr.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.mohesr.example.com
      - peer1.mohesr.example.com
      - peer0.asu.example.com
      - peer1.asu.example.com
    networks:
      - byfn
